#!/bin/bash
# CI Fix Capability - Analyzes and fixes common CI/CD failures

# Don't exit on error - let the router handle error tracking
set +e

# Load shared utilities
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../../shared/utils.sh"
source "$SCRIPT_DIR/../../shared/config.sh"

CAPABILITY_NAME="CI-Fix"
LOG_FILE="ci-fix-$(date +%Y%m%d-%H%M%S).log"

log_info "Starting $CAPABILITY_NAME capability..."

# Function to analyze error logs
analyze_error() {
    local log_file="$1"
    
    local output_file="${GITHUB_OUTPUT:-/tmp/agent_outputs.txt}"
    
    # Ensure output file exists and is writable
    touch "$output_file" 2>/dev/null || {
        log_error "Cannot write to output file: $output_file"
        return 1
    }
    
    if [ ! -f "$log_file" ] || [ ! -s "$log_file" ]; then
        log_warning "No log file found or log file is empty - skipping CI-Fix analysis"
        echo "error_type=no_logs" >> "$output_file" 2>/dev/null || log_warning "Could not write to output file"
        echo "fix_action=skip" >> "$output_file" 2>/dev/null || log_warning "Could not write to output file"
        log_info "CI-Fix skipped: No failed workflow logs to analyze"
        return 0
    fi
    
    local error_log=$(tail -100 "$log_file")
    
    # Use GITHUB_OUTPUT if available (GitHub Actions), otherwise use temp file
    local output_file="${GITHUB_OUTPUT:-/tmp/agent_outputs.txt}"
    
    # Set multiline output for error log
    {
        echo "error_log<<EOF"
        echo "$error_log"
        echo "EOF"
    } >> "$output_file"
    
    # Detect common errors
    if echo "$error_log" | grep -q "npm ci.*can only install packages when your package.json and package-lock.json.*are in sync"; then
        log_info "Detected: npm lock file sync error"
        echo "error_type=npm_lock_sync" >> "$output_file"
        echo "fix_action=run_npm_install" >> "$output_file"
    elif echo "$error_log" | grep -q "Missing:.*from lock file"; then
        log_info "Detected: npm missing dependencies"
        echo "error_type=npm_missing_deps" >> "$output_file"
        echo "fix_action=run_npm_install" >> "$output_file"
    elif echo "$error_log" | grep -q "Invalid format\|Unable to process file command.*output"; then
        log_info "Detected: GitHub Actions output format error"
        echo "error_type=github_actions_output_error" >> "$output_file"
        echo "fix_action=fix_output_format" >> "$output_file"
    elif echo "$error_log" | grep -q "Module not found"; then
        log_info "Detected: Missing module"
        echo "error_type=missing_module" >> "$output_file"
        echo "fix_action=install_missing_package" >> "$output_file"
    elif echo "$error_log" | grep -q "SyntaxError\|ParseError"; then
        log_info "Detected: Syntax error"
        echo "error_type=syntax_error" >> "$output_file"
        echo "fix_action=review_code" >> "$output_file"
    else
        log_warning "Unknown error type detected"
        echo "error_type=unknown" >> "$output_file"
        echo "fix_action=manual_review" >> "$output_file"
    fi
}

# Function to fix npm lock sync issues
fix_npm_lock_sync() {
    log_info "Fixing npm lock file sync issue..."
    
    npm install
    
    if [ -n "$(git status --porcelain package-lock.json)" ]; then
        log_success "package-lock.json updated"
        local output_file="${GITHUB_OUTPUT:-/tmp/agent_outputs.txt}"
        echo "lock_file_changed=true" >> "$output_file"
        
        if [ "$CI_FIX_AUTO_COMMIT" = "true" ]; then
            commit_and_push "Auto-fix: Update package-lock.json to sync with package.json" "package-lock.json"
            log_success "Changes committed and pushed"
        fi
    else
        log_info "No changes to package-lock.json"
        local output_file="${GITHUB_OUTPUT:-/tmp/agent_outputs.txt}"
        echo "lock_file_changed=false" >> "$output_file"
    fi
}

# Function to create issue for unknown errors
create_error_issue() {
    local error_type="$1"
    local error_log="$2"
    local workflow_name="$3"
    
    local title="CI Failure Detected - Requires Manual Review"
    local body="## Error Analysis

**Error Type**: $error_type
**Workflow**: $workflow_name

## Error Log
\`\`\`
$error_log
\`\`\`

## Next Steps
This error requires manual review. The Unified Autonomous Agent was unable to automatically fix this issue.

---
*Generated by $AGENT_NAME - $CAPABILITY_NAME capability*"
    
    create_github_issue "$title" "$body" "ci-failure,needs-review"
    log_info "Created GitHub issue for error type: $error_type"
}

# Main execution
main() {
    local workflow_logs="${1:-workflow_logs.txt}"
    
    log_info "Analyzing workflow logs: $workflow_logs"
    
    # Read outputs from analyze_error function (set via $GITHUB_OUTPUT in GitHub Actions)
    # For local execution, we'll use a temp file
    local output_file="${GITHUB_OUTPUT:-/tmp/agent_outputs.txt}"
    
    # Ensure output file exists
    touch "$output_file" 2>/dev/null || {
        log_error "Cannot create output file: $output_file"
        return 1
    }
    
    # Analyze error - if it returns non-zero, exit with error
    if ! analyze_error "$workflow_logs"; then
        log_error "Failed to analyze error logs"
        return 1
    fi
    
    local error_type=$(grep '^error_type=' "$output_file" 2>/dev/null | cut -d'=' -f2 || echo "unknown")
    local fix_action=$(grep '^fix_action=' "$output_file" 2>/dev/null | cut -d'=' -f2 || echo "skip")
    
    # If no logs found, skip all processing
    if [ "$error_type" = "no_logs" ] || [ "$fix_action" = "skip" ]; then
        log_info "Skipping CI-Fix: No logs to analyze"
        return 0
    fi
    
    case "$error_type" in
        npm_lock_sync|npm_missing_deps)
            fix_npm_lock_sync
            ;;
        github_actions_output_error|syntax_error|unknown)
            if [ -f "$workflow_logs" ] && [ -s "$workflow_logs" ]; then
                local error_log=$(cat "$workflow_logs" | tail -100)
                create_error_issue "$error_type" "$error_log" "${GITHUB_WORKFLOW:-Unknown}"
            else
                log_warning "Cannot create issue: log file not available"
            fi
            ;;
        *)
            log_info "No action needed for error type: $error_type"
            ;;
    esac
    
    log_success "$CAPABILITY_NAME capability completed"
    return 0
}

# Run if executed directly
if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    main "$@"
fi

